apiVersion: apps/v1
kind: Deployment
metadata:
  name: youhungry-deployment
spec:
  selector:
        matchLabels:
          app: youhungryimage-deployment
  replicas: 2
  template:
        metadata:
          labels:
                app: youhungryimage-deployment
        spec:
          containers:
          - name: youhungryimage-deployment
            image: iad.ocir.io/idolbhntaf5o/youhungry/youhungryimage:version1.0
            imagePullPolicy: Always
            ports:
            - containerPort: 3000
          imagePullSecrets:
          - name: ocirsecret
---
apiVersion: v1
kind: Service   
metadata:
  name: youhungry-server
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
        app: youhungryimage-deployment